apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        ports:
          - containerPort: 8080
            protocol: TCP
        image: 060735095223.dkr.ecr.us-east-1.amazonaws.com/application_repo:v1.0