apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name:  app
spec:
  containers:
    - name: app
      image: 060735095223.dkr.ecr.us-east-1.amazonaws.com/application_repo:v1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      